4ALLPORTAL/helm-charts

- charts/4allportal/Chart.lock
- charts/4allportal/Chart.yaml
- charts/4allportal/README.md
- charts/base-cluster/Chart.lock
- charts/base-cluster/Chart.yaml
- charts/base-cluster/README.md
- charts/base-cluster/dashboards/4allportal/metrics.json
- charts/maxscale/Chart.yaml
- charts/maxscale/README.md
> feat(base-cluster): 4allportal-metrics - stack asset count

- charts/4allportal/Chart.yaml
- charts/4allportal/README.md
- charts/4allportal/templates/4allportal/deployment.yaml
> fix(4allportal): mail configuration

- charts/base-cluster/Chart.yaml
- charts/base-cluster/README.md
- charts/base-cluster/templates/monitoring/rules/entropy.yaml
Set threshold warning to state of the art value
> fix(base-cluster): Update Entropy threshold

- charts/4allportal/Chart.yaml
- charts/4allportal/README.md
Add missing version bump after dependency update (maxscale 4.10)
> chore(4allportal): Version bump

- charts/base-cluster/Chart.yaml
- charts/base-cluster/README.md
- charts/base-cluster/templates/security/trivy.yaml
reformat private image registry
> fix(base-cluster): trivy-chart

- charts/base-cluster/Chart.yaml
- charts/base-cluster/README.md
- charts/base-cluster/templates/monitoring/rules/high-storage-usage.yaml
new rule for prometheus (high storage alert)
> feat(base-cluster): create high-storage-usage prometheus rule

- charts/4allportal/Chart.yaml
- charts/4allportal/README.md
- charts/4allportal/templates/webdav/configmap.yaml
> fix(4allportal): indesign needs ._ files to properly work with webdav

- charts/maxscale/Chart.yaml
- charts/maxscale/README.md
- charts/maxscale/values.yaml
I did a new branch with a reverted release, before im chaging again to the new 4.1.6. @tasches please review if this is the correct way. 
Closes CL-57 https://jira.4allportal.net/browse/CL-57
> fix(maxscale): fixing false release and serviceMonitor selector

- charts/maxscale/Chart.lock
- charts/maxscale/Chart.yaml
- charts/maxscale/README.md
- charts/maxscale/templates/deployment.yaml
For ticket CL-37
https://jira.4allportal.net/browse/CL-37
> fix(maxscale): livenessprobe maxscale update

- charts/base-cluster/Chart.yaml
- charts/base-cluster/README.md
- charts/base-cluster/templates/monitoring/rules/high-storage-usage.yaml
threshold ajusted.
add label for alertmanager
> fix(base-cluster): highstorage alert threshold

- charts/base-cluster/Chart.yaml
- charts/base-cluster/README.md
- charts/base-cluster/templates/backup/stash.yaml
> chore(base-cluster): update stash chart to latest version

- charts/base-cluster/Chart.yaml
- charts/base-cluster/README.md
- charts/base-cluster/README.md.gotmpl
- charts/base-cluster/templates/ingress/traefik.yaml
> fix(base-cluster): traefik crds

- charts/base-cluster/Chart.yaml
- charts/base-cluster/README.md
- charts/base-cluster/templates/rbac/users.yaml
Remove upper-case characters from 5-character-token at secret-name-end
> fix(base-cluster): secret for base-cluster SAs

- charts/maxscale/Chart.yaml
- charts/maxscale/README.md
- charts/maxscale/templates/deployment.yaml
I forgot to add the key for configuring the maxSkew.
Ref.: https://github.com/4ALLPORTAL/helm-charts/pull/177#discussion_r1275450362
> fix(maxscale): correct usage of maxskew

- charts/4allportal/Chart.yaml
- charts/4allportal/README.md
- charts/4allportal/templates/webdav/configmap.yaml
- charts/4allportal/templates/webdav/deployment.yaml
- charts/4allportal/values.yaml
- charts/base-cluster/README.md
https://gitlab.4allportal.net/external/webdav-events/-/issues/2
> feat(4allportal): add shared volume and bash image with script for publishing WebDAV events

- charts/4allportal/Chart.yaml
- charts/4allportal/README.md
- charts/4allportal/templates/4allportal/deployment.yaml
I removed the k8s restart app, as it is not required anymore and also currently not working :)
> fix(4allportal): remove app k8s-restart

- charts/4allportal/Chart.yaml
- charts/4allportal/README.md
- charts/4allportal/templates/4allportal/deployment.yaml
- charts/4allportal/templates/_helpers.tpl
- charts/4allportal/templates/validation.tpl
- charts/4allportal/values.schema.json
Chart version increase
values.schema.json updated to reflect all possibilities
.tpl files updated to include check for operator and set 4ALLPORTAL values accordingly
> fix(4allportal): split operator and existing

- charts/4allportal/Chart.yaml
- charts/4allportal/README.md
- charts/4allportal/templates/_helpers.tpl
- charts/4allportal/templates/webdav/configmap.yaml
- charts/4allportal/values.yaml
set webdav mountpoint hardcode in configmap
remove configurable value from values.yaml
add release notes for Chart v20.0.0
increase Chart to 20.0.1
> fix(4allportal): incorrect webdav mount

- charts/4allportal/Chart.yaml
- charts/4allportal/README.md
- charts/4allportal/templates/_helpers.tpl
- charts/4allportal/templates/webdav/configmap.yaml
fix passing of systemApiKey to cURL
increase Chart version (patch)
> fix(4allportal): fix webdav notifications

- charts/base-cluster/Chart.yaml
- charts/base-cluster/README.md
- charts/base-cluster/README.md.gotmpl
- charts/base-cluster/templates/monitoring/rules/hikaricp.yaml
- charts/base-cluster/templates/monitoring/rules/node.yaml
Add alerting rules for Node Memory / CPU usage
Add alerting rules for HikariCP (max|used) connections
> feat(base-cluster): alert rules

- charts/4allportal/Chart.yaml
- charts/4allportal/README.md
- charts/4allportal/values.yaml
tracing disabled by default, not necessary out of the box
> feat(4allportal): disable tracing

- charts/4allportal/Chart.yaml
- charts/4allportal/README.md
- charts/4allportal/values.yaml
Resolves branch 232
Required manual PR due to merge muck-up in IDE
> feat(4allportal): update httpd version

- charts/4allportal/Chart.yaml
- charts/4allportal/README.md
- charts/4allportal/templates/4allportal/ingress.yaml
- charts/4allportal/templates/samba/service.yaml
add Ingress pointing to samba-server service
add required labels to samba Service for websocket forward
> feat(4allportal): configure samba ingress
